#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace house_crud.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="housemanagment")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserthouse(house instance);
    partial void Updatehouse(house instance);
    partial void Deletehouse(house instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<house> houses
		{
			get
			{
				return this.GetTable<house>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.houses")]
	public partial class house : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _house_number;
		
		private string _owner_name;
		
		private string _house_address;
		
		private string _nearest_place;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhouse_numberChanging(int value);
    partial void Onhouse_numberChanged();
    partial void Onowner_nameChanging(string value);
    partial void Onowner_nameChanged();
    partial void Onhouse_addressChanging(string value);
    partial void Onhouse_addressChanged();
    partial void Onnearest_placeChanging(string value);
    partial void Onnearest_placeChanged();
    #endregion
		
		public house()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_house_number", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int house_number
		{
			get
			{
				return this._house_number;
			}
			set
			{
				if ((this._house_number != value))
				{
					this.Onhouse_numberChanging(value);
					this.SendPropertyChanging();
					this._house_number = value;
					this.SendPropertyChanged("house_number");
					this.Onhouse_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_name", DbType="NVarChar(50)")]
		public string owner_name
		{
			get
			{
				return this._owner_name;
			}
			set
			{
				if ((this._owner_name != value))
				{
					this.Onowner_nameChanging(value);
					this.SendPropertyChanging();
					this._owner_name = value;
					this.SendPropertyChanged("owner_name");
					this.Onowner_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_house_address", DbType="NVarChar(50)")]
		public string house_address
		{
			get
			{
				return this._house_address;
			}
			set
			{
				if ((this._house_address != value))
				{
					this.Onhouse_addressChanging(value);
					this.SendPropertyChanging();
					this._house_address = value;
					this.SendPropertyChanged("house_address");
					this.Onhouse_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nearest_place", DbType="NVarChar(50)")]
		public string nearest_place
		{
			get
			{
				return this._nearest_place;
			}
			set
			{
				if ((this._nearest_place != value))
				{
					this.Onnearest_placeChanging(value);
					this.SendPropertyChanging();
					this._nearest_place = value;
					this.SendPropertyChanged("nearest_place");
					this.Onnearest_placeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
