<?xml version="1.0" encoding="utf-8"?><Database Name="empmvc" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.emp_rec" Member="emp_recs">
    <Type Name="emp_rec">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="emp_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="emp_dept" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>