<?xml version="1.0" encoding="utf-8"?><Database Name="abcds1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.students" Member="students">
    <Type Name="student">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AGE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CITY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>