//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efprac
{
    using System;
    using System.Collections.Generic;
    
    public partial class house_records
    {
        public int id { get; set; }
        public string owner_name { get; set; }
        public string house_address { get; set; }
    }
}
