//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agpracef
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_records
    {
        public int student_id { get; set; }
        public string student_name { get; set; }
        public string father_name { get; set; }
        public string department { get; set; }
    }
}
